global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['65.0.124.80:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['65.0.124.80:9100']
